pXO2s = [
        {'name': 'pXO2', 'input': 'gbk', 'file': 'NC_007323.gbk',
         'acc': 'NC_007323', 'size': 95, 'order': 1, 'nudge': 0,
         'offset': 0, 'exclude': (0, 0),
         'defline': 'Bacillus anthracis str. Ames Ancestor plasmid pXO2'},
        {'name': 'pCI-XO2', 'input': 'gbk', 'file': 'NC_014332.gbk',
         'acc': 'NC_014332', 'size': 94, 'order': 2, 'nudge': 0,
         'offset': 898, 'exclude': (0, 0),
         'defline': 'Bacillus cereus biovar anthracis str. CI plasmid pCI-XO2'},
        {'name': 'pAW63', 'input': 'gbk', 'file': 'DQ025752.gbk',
         'acc': 'DQ025752', 'size': 72, 'order': 3, 'nudge': 0,
         'offset': 0, 'exclude': (0, 0),
         'defline': 'Bacillus thuringiensis sv kurstaki str. HD73 plasmid pAW63'},
        {'name': 'pBT9727', 'input': 'gbk', 'file': 'NC_006578.gbk',
         'acc': 'NC_006578', 'size': 77, 'order': 4, 'nudge': 0,
         'offset': 76547, 'exclude': (0, 0),
         'defline': 'Bacillus thuringiensis sv konkukian str. 97-27 plasmid pBT9727'},
#         {'name': 'pBWB402', 'input': 'gbk', 'file': 'NC_010181.gbk',
#          'acc': 'NC_010181', 'size': 75, 'order': 5, 'nudge': 0,
#          'offset': 0, 'exclude': (0, 0),
#          'defline': 'Bacillus weihenstephanensis KBAB4 plasmid pBWB402'},
#         {'name': 'p03BB108_X2', 'input': 'gbk', 'file': 'p03BB108_X2.gbk',
#          'acc': '', 'size': 85, 'order': 5, 'nudge': 0,
#          'offset': 0, 'exclude': (0, 0),
#          'defline': 'Bacillus cereus 03BB108 plasmid construct p03BB108_X2'},
#         {'name': 'p4BA1_X2', 'input': 'gbk', 'file': 'p4BA1_X2.gbk',
#          'acc': '', 'size': 68, 'order': 5, 'nudge': 0,
#          'offset': 0, 'exclude': (0, 0),
#          'defline': 'Bacillus cereus BGSC4BA1 plasmid construct p4BA1_X2'},
#         {'name': 'pRock1-15_X2', 'input': 'gbk', 'file': 'pRock1-15_X2.gbk',
#          'acc': '', 'size': 73, 'order': 5, 'nudge': 0,
#          'offset': 0, 'exclude': (0, 0),
#          'defline': 'Bacillus cereus Rock1-15 plasmid construct pRock1-15_X2'},
]