all = [
        {'name': 'T04001', 'input': 'fas', 'file': 'NZ_ACNB0.fas', 'acc': 'NZ_ACNB0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv sotto str. T04001'},
        {'name': '03BB108', 'input': 'fas', 'file': 'NZ_ABDM0.fas', 'acc': 'NZ_ABDM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus 03BB108'},
        {'name': '172560W', 'input': 'fas', 'file': 'NZ_ACLV0.fas', 'acc': 'NZ_ACLV0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus 172560W'},
        {'name': 'AH1134', 'input': 'fas', 'file': 'NZ_ABDA0.fas', 'acc': 'NZ_ABDA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1134'},
        {'name': 'AH1271', 'input': 'fas', 'file': 'NZ_ACMR0.fas', 'acc': 'NZ_ACMR0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1271'},
        {'name': 'AH1272', 'input': 'fas', 'file': 'NZ_ACMS0.fas', 'acc': 'NZ_ACMS0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1272'},
        {'name': 'AH1273', 'input': 'fas', 'file': 'NZ_ACMT0.fas', 'acc': 'NZ_ACMT0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1273'},
        {'name': 'AH603', 'input': 'fas', 'file': 'NZ_ACMP0.fas', 'acc': 'NZ_ACMP0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH603'},
        {'name': 'ATCC10792', 'input': 'fas', 'file': 'NZ_ACNF0.fas', 'acc': 'NZ_ACNF0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'berliner ATCC 10792'},
        {'name': 'F65185', 'input': 'fas', 'file': 'NZ_ACMO0.fas', 'acc': 'NZ_ACMO0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus F65185'},
        {'name': 'R309803', 'input': 'fas', 'file': 'NZ_ACLY0.fas', 'acc': 'NZ_ACLY0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus R309803'},
        {'name': 'ATCC10876', 'input': 'fas', 'file': 'NZ_ACLT0.fas', 'acc': 'NZ_ACLT0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus ATCC 10876'},
        {'name': 'BDRD-ST26', 'input': 'fas', 'file': 'NZ_ACMC0.fas', 'acc': 'NZ_ACMC0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST26'},
        {'name': 'BGSC4AJ1', 'input': 'fas', 'file': 'NZ_ACNE0.fas', 'acc': 'NZ_ACNE0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4AJ1'},
        {'name': 'BGSC4BD1', 'input': 'fas', 'file': 'NZ_ACNI0.fas', 'acc': 'NZ_ACNI0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4BD1'},
        {'name': 'BGSC4CC1', 'input': 'fas', 'file': 'NZ_ACNJ0.fas', 'acc': 'NZ_ACNJ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4CC1'},
        {'name': 'IBL200', 'input': 'fas', 'file': 'NZ_ACNK0.fas', 'acc': 'NZ_ACNK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis IBL 200'},
        {'name': 'T01001', 'input': 'fas', 'file': 'NZ_ACNA0.fas', 'acc': 'NZ_ACNA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv thuringiensis str. T01001'},
        {'name': 'Rock1-15', 'input': 'fas', 'file': 'NZ_ACMH0.fas', 'acc': 'NZ_ACMH0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock1-15'},
        {'name': 'ATCC35646', 'input': 'fas', 'file': 'NZ_AAJM0.fas', 'acc': 'NZ_AAJM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis serovar israelensis ATCC 35646'},
        {'name': 'H308197', 'input': 'fas', 'file': 'NZ_ABDL0.fas', 'acc': 'NZ_ABDL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus H3081.97'},
        {'name': 'm1293', 'input': 'fas', 'file': 'NZ_ACLS0.fas', 'acc': 'NZ_ACLS0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus m1293'},
        {'name': 'BGSC6E1', 'input': 'fas', 'file': 'NZ_ACLU0.fas', 'acc': 'NZ_ACLU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 6E1'},
        {'name': 'MM3', 'input': 'fas', 'file': 'NZ_ACLW0.fas', 'acc': 'NZ_ACLW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus MM3'},
        {'name': 'AH621', 'input': 'fas', 'file': 'NZ_ACLX0.fas', 'acc': 'NZ_ACLX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH621'},
        {'name': 'ATCC4342', 'input': 'fas', 'file': 'NZ_ACLZ0.fas', 'acc': 'NZ_ACLZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus ATCC 4342'},
        {'name': 'm1550', 'input': 'fas', 'file': 'NZ_ACMA0.fas', 'acc': 'NZ_ACMA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus m1550'},
        {'name': 'BDRD-ST24', 'input': 'fas', 'file': 'NZ_ACMB0.fas', 'acc': 'NZ_ACMB0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST24'},
        {'name': 'BDRD-ST196', 'input': 'fas', 'file': 'NZ_ACMD0.fas', 'acc': 'NZ_ACMD0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST196'},
        {'name': 'BDRD-Cer4', 'input': 'fas', 'file': 'NZ_ACME0.fas', 'acc': 'NZ_ACME0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-Cer4'},
        {'name': '95_8201', 'input': 'fas', 'file': 'NZ_ACMF0.fas', 'acc': 'NZ_ACMF0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus 95/8201'},
        {'name': 'Rock1-3', 'input': 'fas', 'file': 'NZ_ACMG0.fas', 'acc': 'NZ_ACMG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock1-3'},
        {'name': 'Rock3-28', 'input': 'fas', 'file': 'NZ_ACMI0.fas', 'acc': 'NZ_ACMI0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-28'},
        {'name': 'Rock3-29', 'input': 'fas', 'file': 'NZ_ACMJ0.fas', 'acc': 'NZ_ACMJ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-29'},
        {'name': 'Rock3-42', 'input': 'fas', 'file': 'NZ_ACMK0.fas', 'acc': 'NZ_ACMK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-42'},
        {'name': 'Rock3-44', 'input': 'fas', 'file': 'NZ_ACML0.fas', 'acc': 'NZ_ACML0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-44'},
        {'name': 'Rock4-2', 'input': 'fas', 'file': 'NZ_ACMM0.fas', 'acc': 'NZ_ACMM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock4-2'},
        {'name': 'Rock4-18', 'input': 'fas', 'file': 'NZ_ACMN0.fas', 'acc': 'NZ_ACMN0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock4-18'},
        {'name': 'AH676', 'input': 'fas', 'file': 'NZ_ACMQ0.fas', 'acc': 'NZ_ACMQ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH676'},
        {'name': 'DSM2048', 'input': 'fas', 'file': 'NZ_ACMU0.fas', 'acc': 'NZ_ACMU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides DSM 2048'},
        {'name': 'Rock1-4', 'input': 'fas', 'file': 'NZ_ACMV0.fas', 'acc': 'NZ_ACMV0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides Rock1-4'},
        {'name': 'Rock3-17', 'input': 'fas', 'file': 'NZ_ACMW0.fas', 'acc': 'NZ_ACMW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides Rock3-17'},
        {'name': 'DSM12442', 'input': 'fas', 'file': 'NZ_ACMX0.fas', 'acc': 'NZ_ACMX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus pseudomycoides DSM 12442'},
        {'name': 'BGSC4Y1', 'input': 'fas', 'file': 'NZ_ACMY0.fas', 'acc': 'NZ_ACMY0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4Y1'},
        {'name': 'Bt407', 'input': 'fas', 'file': 'NZ_ACMZ0.fas', 'acc': 'NZ_ACMZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bt407'},
        {'name': 'T13001', 'input': 'fas', 'file': 'NZ_ACNC0.fas', 'acc': 'NZ_ACNC0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv pakistani str. T13001'},
        {'name': 'T03a001', 'input': 'fas', 'file': 'NZ_ACND0.fas', 'acc': 'NZ_ACND0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv kurstaki str. T03a001'},
        {'name': 'BGSC4AW1', 'input': 'fas', 'file': 'NZ_ACNG0.fas', 'acc': 'NZ_ACNG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4AW1'},
        {'name': 'BGSC4BA1', 'input': 'fas', 'file': 'NZ_ACNH0.fas', 'acc': 'NZ_ACNH0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4BA1'},
        {'name': 'IBL4222', 'input': 'fas', 'file': 'NZ_ACNL0.fas', 'acc': 'NZ_ACNL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis IBL 4222'},
        {'name': 'SJ1', 'input': 'fas', 'file': 'NZ_ADFM0.fas', 'acc': 'NZ_ADFM0',  'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus SJ1'}
]

pXO1_positives = [ # 20
        {'name': 'T04001', 'input': 'fas', 'file': 'NZ_ACNB0.fas', 'acc': 'NZ_ACNB0', 'size': 0, 'offset': (0, 142551), 'exclude': (367,453), 'defline': 'Bacillus thuringiensis sv sotto str. T04001'},
        {'name': '03BB108', 'input': 'fas', 'file': 'NZ_ABDM0.fas', 'acc': 'NZ_ABDM0', 'size': 0, 'offset': (0,0), 'exclude': (1,2,7), 'defline': 'Bacillus cereus 03BB108'},
        {'name': '172560W', 'input': 'fas', 'file': 'NZ_ACLV0.fas', 'acc': 'NZ_ACLV0', 'size': 0, 'offset': (0, 19174), 'exclude': (71,116,126), 'defline': 'Bacillus cereus 172560W'},
        {'name': 'AH1134', 'input': 'fas', 'file': 'NZ_ABDA0.fas', 'acc': 'NZ_ABDA0', 'size': 0, 'offset': (0,0), 'exclude': (0,2), 'defline': 'Bacillus cereus AH1134'},
        {'name': 'AH1271', 'input': 'fas', 'file': 'NZ_ACMR0.fas', 'acc': 'NZ_ACMR0', 'size': 0, 'offset': (0, 45176), 'exclude': (140,357), 'defline': 'Bacillus cereus AH1271'},
        {'name': 'AH1272', 'input': 'fas', 'file': 'NZ_ACMS0.fas', 'acc': 'NZ_ACMS0', 'size': 0, 'offset': (0,0), 'exclude': (0,291), 'defline': 'Bacillus cereus AH1272'},
        {'name': 'AH1273', 'input': 'fas', 'file': 'NZ_ACMT0.fas', 'acc': 'NZ_ACMT0', 'size': 0, 'offset': (0,0), 'exclude': (0,396), 'defline': 'Bacillus cereus AH1273'},
        {'name': 'AH603', 'input': 'fas', 'file': 'NZ_ACMP0.fas', 'acc': 'NZ_ACMP0', 'size': 0, 'offset': (0,0), 'exclude': (157,159,160), 'defline': 'Bacillus cereus AH603'},
        {'name': 'ATCC10792', 'input': 'fas', 'file': 'NZ_ACNF0.fas', 'acc': 'NZ_ACNF0', 'size': 0, 'offset': (0, 7668), 'exclude': (57,128,151,167,186), 'defline': 'berliner ATCC 10792'},
        {'name': 'F65185', 'input': 'fas', 'file': 'NZ_ACMO0.fas', 'acc': 'NZ_ACMO0', 'size': 0, 'offset': (0, 10446), 'exclude': (124,159,188,203,218,224,231,234,239,240,243,255), 'defline': 'Bacillus cereus F65185'},
        {'name': 'R309803', 'input': 'fas', 'file': 'NZ_ACLY0.fas', 'acc': 'NZ_ACLY0', 'size': 0, 'offset': (0, 10214), 'exclude': (0, 0), 'defline': 'Bacillus cereus R309803'},
        {'name': 'ATCC10876', 'input': 'fas', 'file': 'NZ_ACLT0.fas', 'acc': 'NZ_ACLT0', 'size': 0, 'offset': (0, 20882), 'exclude': (140,154), 'defline': 'Bacillus cereus ATCC 10876'},
        {'name': 'BDRD-ST26', 'input': 'fas', 'file': 'NZ_ACMC0.fas', 'acc': 'NZ_ACMC0', 'size': 0, 'offset': (0, 31913), 'exclude': (136,144,166,116), 'defline': 'BDRD-ST26'},
        {'name': 'BGSC4AJ1', 'input': 'fas', 'file': 'NZ_ACNE0.fas', 'acc': 'NZ_ACNE0', 'size': 0, 'offset': (0, 129515), 'exclude': (224,138,186,187,180), 'defline': 'BGSC 4AJ1'},
        {'name': 'BGSC4BD1', 'input': 'fas', 'file': 'NZ_ACNI0.fas', 'acc': 'NZ_ACNI0', 'size': 0, 'offset': (0, 41684), 'exclude': (191,212,70,132,251), 'defline': 'BGSC 4BD1'},
        {'name': 'BGSC4CC1', 'input': 'fas', 'file': 'NZ_ACNJ0.fas', 'acc': 'NZ_ACNJ0', 'size': 0, 'offset': (0, 155948), 'exclude': (144,141,208,200,201,202,203,204,205,244,220,248,139,154,136,134,246,197,257), 'defline': 'BGSC 4CC1'},
        {'name': 'IBL200', 'input': 'fas', 'file': 'NZ_ACNK0.fas', 'acc': 'NZ_ACNK0', 'size': 0, 'offset': (0, 29435), 'exclude': (122,125,207,194,235,147,222,145,149,96,242), 'defline': 'Bacillus thuringiensis IBL 200'},
        {'name': 'T01001', 'input': 'fas', 'file': 'NZ_ACNA0.fas', 'acc': 'NZ_ACNA0', 'size': 0, 'offset': (0, 9634), 'exclude': (133,235,182,154,169,118), 'defline': 'Bacillus thuringiensis sv thuringiensis str. T01001'},
        {'name': 'Rock1-15', 'input': 'fas', 'file': 'NZ_ACMH0.fas', 'acc': 'NZ_ACMH0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock1-15'},
        {'name': 'G9241', 'input': 'fas', 'file': 'NZ_AAEK0.fas', 'acc': 'NZ_AAEK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus G9241'} # pBCXO1 available assembled
]

pXO1_negatives = [
        {'name': 'ATCC35646', 'input': 'fas', 'file': 'NZ_AAJM0.fas', 'acc': 'NZ_AAJM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus thuringiensis serovar israelensis ATCC 35646'},
        {'name': 'H308197', 'input': 'fas', 'file': 'NZ_ABDL0.fas', 'acc': 'NZ_ABDL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus H3081.97'},
        {'name': 'm1293', 'input': 'fas', 'file': 'NZ_ACLS0.fas', 'acc': 'NZ_ACLS0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus m1293'},
        {'name': 'BGSC6E1', 'input': 'fas', 'file': 'NZ_ACLU0.fas', 'acc': 'NZ_ACLU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BGSC 6E1'},
        {'name': 'MM3', 'input': 'fas', 'file': 'NZ_ACLW0.fas', 'acc': 'NZ_ACLW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus MM3'},
        {'name': 'AH621', 'input': 'fas', 'file': 'NZ_ACLX0.fas', 'acc': 'NZ_ACLX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus AH621'},
        {'name': 'ATCC4342', 'input': 'fas', 'file': 'NZ_ACLZ0.fas', 'acc': 'NZ_ACLZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus ATCC 4342'},
        {'name': 'm1550', 'input': 'fas', 'file': 'NZ_ACMA0.fas', 'acc': 'NZ_ACMA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus m1550'},
        {'name': 'BDRD-ST24', 'input': 'fas', 'file': 'NZ_ACMB0.fas', 'acc': 'NZ_ACMB0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BDRD-ST24'},
        {'name': 'BDRD-ST196', 'input': 'fas', 'file': 'NZ_ACMD0.fas', 'acc': 'NZ_ACMD0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BDRD-ST196'},
        {'name': 'BDRD-Cer4', 'input': 'fas', 'file': 'NZ_ACME0.fas', 'acc': 'NZ_ACME0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BDRD-Cer4'},
        {'name': '95_8201', 'input': 'fas', 'file': 'NZ_ACMF0.fas', 'acc': 'NZ_ACMF0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus 95/8201'},
        {'name': 'Rock1-3', 'input': 'fas', 'file': 'NZ_ACMG0.fas', 'acc': 'NZ_ACMG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock1-3'},
        {'name': 'Rock3-28', 'input': 'fas', 'file': 'NZ_ACMI0.fas', 'acc': 'NZ_ACMI0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock3-28'},
        {'name': 'Rock3-29', 'input': 'fas', 'file': 'NZ_ACMJ0.fas', 'acc': 'NZ_ACMJ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock3-29'},
        {'name': 'Rock3-42', 'input': 'fas', 'file': 'NZ_ACMK0.fas', 'acc': 'NZ_ACMK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock3-42'},
        {'name': 'Rock3-44', 'input': 'fas', 'file': 'NZ_ACML0.fas', 'acc': 'NZ_ACML0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock3-44'},
        {'name': 'Rock4-2', 'input': 'fas', 'file': 'NZ_ACMM0.fas', 'acc': 'NZ_ACMM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock4-2'},
        {'name': 'Rock4-18', 'input': 'fas', 'file': 'NZ_ACMN0.fas', 'acc': 'NZ_ACMN0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus Rock4-18'},
        {'name': 'AH676', 'input': 'fas', 'file': 'NZ_ACMQ0.fas', 'acc': 'NZ_ACMQ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus AH676'},
        {'name': 'DSM2048', 'input': 'fas', 'file': 'NZ_ACMU0.fas', 'acc': 'NZ_ACMU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus mycoides DSM 2048'},
        {'name': 'Rock1-4', 'input': 'fas', 'file': 'NZ_ACMV0.fas', 'acc': 'NZ_ACMV0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus mycoides Rock1-4'},
        {'name': 'Rock3-17', 'input': 'fas', 'file': 'NZ_ACMW0.fas', 'acc': 'NZ_ACMW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus mycoides Rock3-17'},
        {'name': 'DSM12442', 'input': 'fas', 'file': 'NZ_ACMX0.fas', 'acc': 'NZ_ACMX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus pseudomycoides DSM 12442'},
        {'name': 'BGSC4Y1', 'input': 'fas', 'file': 'NZ_ACMY0.fas', 'acc': 'NZ_ACMY0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BGSC 4Y1'},
        {'name': 'Bt407', 'input': 'fas', 'file': 'NZ_ACMZ0.fas', 'acc': 'NZ_ACMZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bt407'},
        {'name': 'T13001', 'input': 'fas', 'file': 'NZ_ACNC0.fas', 'acc': 'NZ_ACNC0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus thuringiensis sv pakistani str. T13001'},
        {'name': 'T03a001', 'input': 'fas', 'file': 'NZ_ACND0.fas', 'acc': 'NZ_ACND0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus thuringiensis sv kurstaki str. T03a001'},
        {'name': 'BGSC4AW1', 'input': 'fas', 'file': 'NZ_ACNG0.fas', 'acc': 'NZ_ACNG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BGSC 4AW1'},
        {'name': 'BGSC4BA1', 'input': 'fas', 'file': 'NZ_ACNH0.fas', 'acc': 'NZ_ACNH0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'BGSC 4BA1'},
        {'name': 'IBL4222', 'input': 'fas', 'file': 'NZ_ACNL0.fas', 'acc': 'NZ_ACNL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus thuringiensis IBL 4222'},
        {'name': 'SJ1', 'input': 'fas', 'file': 'NZ_ADFM0.fas', 'acc': 'NZ_ADFM0',  'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'select': (0), 'defline': 'Bacillus cereus SJ1'}
]

pXO2_positives = [ # 3
        {'name': '03BB108', 'input': 'fas', 'file': 'NZ_ABDM0.fas', 'acc': 'NZ_ABDM0', 'size': 0, 'offset': (0,0), 'exclude': (1,2,4,7,63), 'select': (0,64), 'defline': 'Bacillus cereus 03BB108'},
        {'name': 'BGSC4BA1', 'input': 'fas', 'file': 'NZ_ACNH0.fas', 'acc': 'NZ_ACNH0', 'size': 0, 'offset': (0,0), 'exclude': (24,52,60,173,169), 'select': (125,162), 'defline': 'BGSC 4BA1'},
        {'name': 'Rock1-15', 'input': 'fas', 'file': 'NZ_ACMH0.fas', 'acc': 'NZ_ACMH0', 'size': 0, 'offset': (0,0), 'exclude': (43,185,62,189,190,27), 'select': (0,141), 'defline': 'Bacillus cereus Rock1-15'}
]

pXO2_negatives = [
        {'name': 'T04001', 'input': 'fas', 'file': 'NZ_ACNB0.fas', 'acc': 'NZ_ACNB0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv sotto str. T04001'},
        {'name': '172560W', 'input': 'fas', 'file': 'NZ_ACLV0.fas', 'acc': 'NZ_ACLV0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus 172560W'},
        {'name': 'AH1134', 'input': 'fas', 'file': 'NZ_ABDA0.fas', 'acc': 'NZ_ABDA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1134'},
        {'name': 'AH1271', 'input': 'fas', 'file': 'NZ_ACMR0.fas', 'acc': 'NZ_ACMR0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1271'},
        {'name': 'AH1272', 'input': 'fas', 'file': 'NZ_ACMS0.fas', 'acc': 'NZ_ACMS0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1272'},
        {'name': 'AH1273', 'input': 'fas', 'file': 'NZ_ACMT0.fas', 'acc': 'NZ_ACMT0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH1273'},
        {'name': 'AH603', 'input': 'fas', 'file': 'NZ_ACMP0.fas', 'acc': 'NZ_ACMP0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH603'},
        {'name': 'ATCC10792', 'input': 'fas', 'file': 'NZ_ACNF0.fas', 'acc': 'NZ_ACNF0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'berliner ATCC 10792'},
        {'name': 'F65185', 'input': 'fas', 'file': 'NZ_ACMO0.fas', 'acc': 'NZ_ACMO0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus F65185'},
        {'name': 'R309803', 'input': 'fas', 'file': 'NZ_ACLY0.fas', 'acc': 'NZ_ACLY0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus R309803'},
        {'name': 'ATCC10876', 'input': 'fas', 'file': 'NZ_ACLT0.fas', 'acc': 'NZ_ACLT0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus ATCC 10876'},
        {'name': 'BDRD-ST26', 'input': 'fas', 'file': 'NZ_ACMC0.fas', 'acc': 'NZ_ACMC0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST26'},
        {'name': 'BGSC4AJ1', 'input': 'fas', 'file': 'NZ_ACNE0.fas', 'acc': 'NZ_ACNE0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4AJ1'},
        {'name': 'BGSC4BD1', 'input': 'fas', 'file': 'NZ_ACNI0.fas', 'acc': 'NZ_ACNI0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4BD1'},
        {'name': 'BGSC4CC1', 'input': 'fas', 'file': 'NZ_ACNJ0.fas', 'acc': 'NZ_ACNJ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4CC1'},
        {'name': 'IBL200', 'input': 'fas', 'file': 'NZ_ACNK0.fas', 'acc': 'NZ_ACNK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis IBL 200'},
        {'name': 'T01001', 'input': 'fas', 'file': 'NZ_ACNA0.fas', 'acc': 'NZ_ACNA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv thuringiensis str. T01001'},
        {'name': 'ATCC35646', 'input': 'fas', 'file': 'NZ_AAJM0.fas', 'acc': 'NZ_AAJM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis serovar israelensis ATCC 35646'},
        {'name': 'H308197', 'input': 'fas', 'file': 'NZ_ABDL0.fas', 'acc': 'NZ_ABDL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus H3081.97'},
        {'name': 'm1293', 'input': 'fas', 'file': 'NZ_ACLS0.fas', 'acc': 'NZ_ACLS0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus m1293'},
        {'name': 'BGSC6E1', 'input': 'fas', 'file': 'NZ_ACLU0.fas', 'acc': 'NZ_ACLU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 6E1'},
        {'name': 'MM3', 'input': 'fas', 'file': 'NZ_ACLW0.fas', 'acc': 'NZ_ACLW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus MM3'},
        {'name': 'AH621', 'input': 'fas', 'file': 'NZ_ACLX0.fas', 'acc': 'NZ_ACLX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH621'},
        {'name': 'ATCC4342', 'input': 'fas', 'file': 'NZ_ACLZ0.fas', 'acc': 'NZ_ACLZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus ATCC 4342'},
        {'name': 'm1550', 'input': 'fas', 'file': 'NZ_ACMA0.fas', 'acc': 'NZ_ACMA0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus m1550'},
        {'name': 'BDRD-ST24', 'input': 'fas', 'file': 'NZ_ACMB0.fas', 'acc': 'NZ_ACMB0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST24'},
        {'name': 'BDRD-ST196', 'input': 'fas', 'file': 'NZ_ACMD0.fas', 'acc': 'NZ_ACMD0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-ST196'},
        {'name': 'BDRD-Cer4', 'input': 'fas', 'file': 'NZ_ACME0.fas', 'acc': 'NZ_ACME0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BDRD-Cer4'},
        {'name': '95_8201', 'input': 'fas', 'file': 'NZ_ACMF0.fas', 'acc': 'NZ_ACMF0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus 95/8201'},
        {'name': 'Rock1-3', 'input': 'fas', 'file': 'NZ_ACMG0.fas', 'acc': 'NZ_ACMG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock1-3'},
        {'name': 'Rock3-28', 'input': 'fas', 'file': 'NZ_ACMI0.fas', 'acc': 'NZ_ACMI0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-28'},
        {'name': 'Rock3-29', 'input': 'fas', 'file': 'NZ_ACMJ0.fas', 'acc': 'NZ_ACMJ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-29'},
        {'name': 'Rock3-42', 'input': 'fas', 'file': 'NZ_ACMK0.fas', 'acc': 'NZ_ACMK0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-42'},
        {'name': 'Rock3-44', 'input': 'fas', 'file': 'NZ_ACML0.fas', 'acc': 'NZ_ACML0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock3-44'},
        {'name': 'Rock4-2', 'input': 'fas', 'file': 'NZ_ACMM0.fas', 'acc': 'NZ_ACMM0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock4-2'},
        {'name': 'Rock4-18', 'input': 'fas', 'file': 'NZ_ACMN0.fas', 'acc': 'NZ_ACMN0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus Rock4-18'},
        {'name': 'AH676', 'input': 'fas', 'file': 'NZ_ACMQ0.fas', 'acc': 'NZ_ACMQ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus AH676'},
        {'name': 'DSM2048', 'input': 'fas', 'file': 'NZ_ACMU0.fas', 'acc': 'NZ_ACMU0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides DSM 2048'},
        {'name': 'Rock1-4', 'input': 'fas', 'file': 'NZ_ACMV0.fas', 'acc': 'NZ_ACMV0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides Rock1-4'},
        {'name': 'Rock3-17', 'input': 'fas', 'file': 'NZ_ACMW0.fas', 'acc': 'NZ_ACMW0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus mycoides Rock3-17'},
        {'name': 'DSM12442', 'input': 'fas', 'file': 'NZ_ACMX0.fas', 'acc': 'NZ_ACMX0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus pseudomycoides DSM 12442'},
        {'name': 'BGSC4Y1', 'input': 'fas', 'file': 'NZ_ACMY0.fas', 'acc': 'NZ_ACMY0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4Y1'},
        {'name': 'Bt407', 'input': 'fas', 'file': 'NZ_ACMZ0.fas', 'acc': 'NZ_ACMZ0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bt407'},
        {'name': 'T13001', 'input': 'fas', 'file': 'NZ_ACNC0.fas', 'acc': 'NZ_ACNC0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv pakistani str. T13001'},
        {'name': 'T03a001', 'input': 'fas', 'file': 'NZ_ACND0.fas', 'acc': 'NZ_ACND0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis sv kurstaki str. T03a001'},
        {'name': 'BGSC4AW1', 'input': 'fas', 'file': 'NZ_ACNG0.fas', 'acc': 'NZ_ACNG0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'BGSC 4AW1'},
        {'name': 'IBL4222', 'input': 'fas', 'file': 'NZ_ACNL0.fas', 'acc': 'NZ_ACNL0', 'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus thuringiensis IBL 4222'},
        {'name': 'SJ1', 'input': 'fas', 'file': 'NZ_ADFM0.fas', 'acc': 'NZ_ADFM0',  'size': 0, 'offset': (0,0), 'exclude': (0, 0), 'defline': 'Bacillus cereus SJ1'}
]

phage_positive = [
        {'name': 'ATCC35646', 'input': 'fas', 'file': 'NZ_AAJM0.fas', 'acc': 'NZ_AAJM0', 'size': 0, 'offset': (0,0), 'select': (106, 0), 'defline': 'Bacillus thuringiensis serovar israelensis ATCC 35646'},
        {'name': 'IBL4222', 'input': 'fas', 'file': 'NZ_ACNL0.fas', 'acc': 'NZ_ACNL0', 'size': 0, 'offset': (0,0), 'select': (363, 0), 'defline': 'Bacillus thuringiensis IBL 4222'}
]